### ISSUE TITLE
Make it work with multiline codec

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-lumberjack#1]
Problem code: https://github.com/logstash-plugins/logstash-input-lumberjack/blob/bd3207e90d2c1121f5f4f814f6ec336facf49095/lib/logstash/inputs/lumberjack.rb#L47-L53

The lumberjack input cannot currently be used with the multiline codec due to the fact that the codec is shared across all lumberjack streams. This causes weird and confusing behavior that events from unrelated log streams are merged into a single event.

**Comment by purbon** [comment]
working on this.

**Comment by suyograo** [comment]
https://github.com/logstash-plugins/logstash-input-lumberjack/pull/5
