### ISSUE TITLE
lumberjack input causing logstash to crash

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-lumberjack#15]
(This issue was originally filed by @cjs226 at https://github.com/elastic/logstash/issues/1489)

---

I'm trying to utilize logstash-forwarder/lumberjack but doing so is causing my logstash server to crash with the following:

{:timestamp=>"2014-07-01T01:49:04.731000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Lumberjack ssl_certificate=>\"/etc/logstash/certs/foo.pem\", ssl_key=>\"/etc/logstash/private/foo.key\", type=>\"lumberjack\", host=>\"0.0.0.0\">\n  Error: Bad file descriptor - Bad file descriptor", :level=>:error}
{:timestamp=>"2014-07-01T01:49:04.732000+0000", :message=>"Plugin is finished", :plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/certs/foo.pem", ssl_key=>"/etc/logstash/private/foo.key", type=>"lumberjack", host=>"0.0.0.0">, :level=>:info}

If I remove lumberjack from the input stanza logstash is stable.

I'm running Logstash v1.4.2 and attempting to use logstash-forwarder v0.3.1 on Ubuntu 12.04.

**Comment by ph** [comment]
From reading the thread in #1489 the root problem seem lack of congestion control, which we now have with a timeout sizequeue and a circuit breaker. Since logstash 1.5.2

**Comment by Jaykah** [comment]
I am experiencing the same issue on logstash 2.0.0

```

UDP listener died {:exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:3682:in `select'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:77:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.3/lib/logstash/inputs/udp.rb:50:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:180:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:174:in `start_input'"], :level=>:warn}
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Lumberjack port=>6000, ssl_certificate=>"/etc/pki/tls/certs/logstash-forwarder.crt", ssl_key=>"/etc/pki/tls/private/logstash-forwarder.key", tags=>["lumberjack"], codec=><LogStash::Codecs::Plain charset=>"UTF-8">, host=>"0.0.0.0", congestion_threshold=>5>
  Error: Bad file descriptor - Bad file descriptor {:level=>:error}
```
