### ISSUE TITLE
"RuntimeError Unknown frame type" using lumberjack input

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-lumberjack#16]
(This issue was originally filed by @OverlordAlex at https://github.com/elastic/logstash/issues/1488)

---

Using a lumberjack input, logstash (v1.4.2) crashes with the above runtime error (frame type 49). The crash is happening fairly regularly: on average, it crashes after receiving 5-15k events, which is about 20-30 seconds running time

This error is very similar to https://logstash.jira.com/browse/LOGSTASH-1851

The error reported on the lumberjack side is 
> Read error looking for ack: EOF

Stack trace from logstash:

RuntimeError: Unknown frame type: 49
  header (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:142
    feed at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
     run at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
     run at (...)/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59

**Comment by ph** [comment]
The lumberjack input wont crash on unhandled exception, since 1.0.4
