### ISSUE TITLE
NoMethodError: undefined method `force_encoding' for nil:NilClass

### ISSUE THREAD

**Issue by jwalton** [logstash-plugins/logstash-input-lumberjack#2]
I'm seeing the following error when sending a message to logstash via lumberjack protocol:

```
NoMethodError: undefined method `force_encoding' for nil:NilClass
           convert at /opt/logstash/lib/logstash/util/charset.rb:14
            decode at /opt/logstash/lib/logstash/codecs/plain.rb:36
               run at /opt/logstash/lib/logstash/inputs/lumberjack.rb:47
              call at org/jruby/RubyProc.java:271
              data at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:241
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:223
  data_field_value at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:182
              feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220
               run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:59
```

This problem appears to have been reported [in JIRA as LOGSTASH-1566](https://logstash.jira.com/browse/LOGSTASH-1566) and there's even a patch there which would fix this, but it's still a problem.

When we reach [this line](https://github.com/logstash-plugins/logstash-input-lumberjack/blob/bd3207e90d2c1121f5f4f814f6ec336facf49095/lib/logstash/inputs/lumberjack.rb#L48), `l` appears to be a hash and not a string, and so strongly resists attempts to "decode" it via UTF-8.

**Comment by jwalton** [comment]
You can recreate this easily by creating a new logstash server with the following input section:

```
input {
  lumberjack {
    codec => noop
    port => 9997
    type => "logs"
    ssl_certificate => "/opt/ssl/logstash.crt"
    ssl_key => "/opt/ssl/logstash.key"
  }
}
```

And then run [this coffeescript file](https://gist.github.com/jwalton/770b6cc8b79120b35cfe) (which will send a lumberjack message.)

If you add a `puts l` right before the call to `@codec.decode()`, then it dumps out:

    {"@timestamp"=>"\"2015-01-12T20:27:14.487Z\"", "@version"=>"1", "name"=>"\"Logger\"", "message"=>"\"Hello world\""}

So the message is being received and parsed correctly by lumberjack up to this point.

**Comment by jwalton** [comment]
Oooh.  I'm starting to understand this; logstash is demanding that I have a `line` key in the record I send up via lumberjack.  That's a bit weird, since the data is already formatted into key/value pairs.  Logstash also doesn't like it if I send a @timestamp like this, because it wants a date instead of a string.  It seems like I'll have to convert my data into some kind of string so I can then parse it back out on the logstash side, the way things are.

**Comment by ph** [comment]
This is related in the use context of lumberjack, which is the logstash-forwarder. Looking at the LSF code
https://github.com/elasticsearch/logstash-forwarder/blob/master/publisher1.go#L223-L239 you can see how the data frame is created.

I think the philosophy of the LSF is to do the least amount of work and only redirect string to a full logstash instance to extracts or parse the data. This is why the `delete(:line)` is hardcoded..

What are you trying to achieve? Create a nodejs logger output to send events directly to a logstash instance?

**Comment by jwalton** [comment]
Yup, that's exactly what I'm doing.  I have a bunch of node.js services running in docker containers, and I want to push their logs to logstash.  I'm using [bunyan-logstash-tcp](https://github.com/chris-rock/bunyan-logstash-tcp) right now, but I want encryption, and I want to make sure messages don't get lost if the connection drops, and sadly bunyna-logstash-tcp does neither of these.

I've got this working by essentially doing:

    sendDataFrame({line: JSON.stringify(myData)})

and then I set the codec on my logstash input to "JSON" and it all works out.  So I suppose you can close this if you like.  :)  It *would* maybe be nice if this was documented somewhere, though, maybe [here](https://github.com/elasticsearch/logstash-forwarder/blob/master/PROTOCOL.md).

**Comment by ph** [comment]
Would be nice to opensource your nodejs lumberjack implementation. Yes the [PROTOCOL.md](https://github.com/elasticsearch/logstash-forwarder/blob/master/PROTOCOL.md) should be the place to have this, I would gladly merge a PR to improve it :)

**Comment by jwalton** [comment]
Yeah, I very definitely will.  Right now it doesn't handle ACKs, so it has a little ways to go.  :)

I'll push a PR for PROTOCOL.md in a day or two - I just got asked to do some "real work".  :P

**Comment by jwalton** [comment]
Client side is here: https://github.com/benbria/node-lumberjack-protocol

And I've written an output stream for Bunyan which uses it: https://github.com/benbria/node-bunyan-lumberjack

A little testing left to do tonight, but there we are.  :)

**Comment by ph** [comment]
Nice!

**Comment by jordansissel** [comment]
Just FYI, lumberjack protocol has a few bugs in it, so by implementing the protocol you're automatically implementing a buggy thing. It needs improvement :)

**Comment by jwalton** [comment]
Haha.  Yeah, if you read my 'caveats' section, you'll see where I deviated
from the spec in terms of window size (I send up to 10x the window size
before I stop sending and wait for an ack, because of the way logstash
acks.)  I also didn't bother to implement compressed frames although I'll
probably get around to trying it eventually.

-Jason
