### ISSUE TITLE
DoS using malcrafted packet

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-lumberjack#20]
(This issue was originally filed by @celesteking at https://github.com/elastic/logstash/issues/3138)

---

It's possible to bring logstash lumberjack input down and thus stop it from accepting logs via following:

```openssl s_client -connect server:port ```
After connection, just write something and press enter. That's enough to trigger error on server:

```
RuntimeError: Unknown frame type: 101
  header at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:149
    feed at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:100
     run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:227
  invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.5/lib/logstash/inputs/lumberjack.rb:71
```

Input is no longer active.

```
# rpm -qf /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.5/lib/logstash/inputs/lumberjack.rb
logstash-1.5.0_rc3-1.noarch
```

**Comment by ph** [comment]
This was fixed in the #43 and the input should keep accepting new connection.
