### ISSUE TITLE
Exception in lumberjack plugin when shutting down

### ISSUE THREAD

**Issue by pvanderlinden** [logstash-plugins/logstash-input-lumberjack#21]
SIGTERM received. Shutting down the pipeline. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"122", :method=>"execute"}
Sending shutdown signal to input thread {:thread=>#<Thread:0x3887db5c sleep>, :level=>:info, :file=>"logstash/pipeline.rb", :line=>"258", :method=>"shutdown"}
Plugin is finished {:plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/lumberjack.crt", ssl_key=>"/etc/logstash/lumberjack.key", host=>"0.0.0.0">, :level=>:info, :file=>"logstash/plugin.rb", :line=>"61", :method=>"finished"}
Exception in lumberjack input {:exception=>#<LogStash::ShutdownSignal: LogStash::ShutdownSignal>, :level=>:error, :file=>"logstash/inputs/lumberjack.rb", :line=>"74", :method=>"run"}
Received shutdown signal {:plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/lumberjack.crt", ssl_key=>"/etc/logstash/lumberjack.key", host=>"0.0.0.0">, :level=>:info, :file=>"logstash/plugin.rb", :line=>"39", :method=>"shutdown"}
Sending shutdown event to agent queue {:plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/lumberjack.crt", ssl_key=>"/etc/logstash/lumberjack.key", host=>"0.0.0.0">, :level=>:info, :file=>"logstash/plugin.rb", :line=>"56", :method=>"finished"}
Sending shutdown event to agent queue {:plugin=><LogStash::Inputs::Lumberjack ssl_certificate=>"/etc/logstash/lumberjack.crt", ssl_key=>"/etc/logstash/lumberjack.key", host=>"0.0.0.0">, :level=>:info, :file=>"logstash/plugin.rb", :line=>"56", :method=>"finished"}

**Comment by ph** [comment]
The shutdown behavior was changed in #53 So this exception should not happen anymore.
