### ISSUE TITLE
Lumberjack is no longer defaulting its codec to "plain"

### ISSUE THREAD

**Issue by russl** [logstash-plugins/logstash-input-lumberjack#27]
Before I upgraded to LS 1.5.0, the default behavior of the lumberjack input was to default to the "plain" codec, if the codec configured did not match the incoming message.

In my situation I am dealing with nginx logs and am formatting the access logs to be json and sending them to lumberjack.  This works as expected.  However, the nginx error logs are not able to be formatted as such.  When these error logs are sent to lumberjack they are tagged with "_jsonparseerror".  Where they were not before

We were relying on the fallback to the "plain" codec.  Is there a different way to deal with this now?

Below is the configuration I are using.

Operating System: Ubuntu 12.04.5 LTS
Ruby Version: 1.9.3
logstash-forwarder: 0.4.0
logstash: 1.5.0-1

logstash-forwarder config:

{
  "network": {
    "servers": [ "<server>:<port>" ],
    "ssl certificate": "/opt/logstash/ssl/logstash-forwarder.crt",
    "ssl key": "/opt/logstash/ssl/logstash-forwarder.key",
    "ssl ca": "/opt/logstash/ssl/logstash-forwarder.crt",
    "timeout": 60
  },
  "files": [
    {
      "paths": ["/mnt/log/nginx/nginx_access.log"],
      "fields": { "logtype": "proxy_access", "environment": "<env>", "personality": "name" }
    },
    {
      "paths": ["/mnt/log/nginx/nginx_error.log"],
      "fields": { "logtype": "proxy_error", "environment": "<env>", "personality": "name" }
    }
  ]
}

lumberjack config:

input {
  lumberjack {
    port => 5739
    ssl_certificate => "/opt/logstash/ssl/logstash-forwarder.crt"
    ssl_key => "/opt/logstash/ssl/logstash-forwarder.key"
    codec => "json"
  }
}

**Comment by jordansissel** [comment]
> We were relying on the fallback

The fallback still occurs. The _jsonparseerror is added to indicate that you told Logstash that you expected JSON, but it did not receive valid JSON. If you do not wish for this tag, you can remove it with a filter:

```
filter {
  mutate {
    remove_tag => "_jsonparsefailure"
  }
}
```

**Comment by jordansissel** [comment]
The change to add the _jsonparsefailure tag was done in 0c4bbd12 and is similar behavior to the grok filter tagging failures with _grokparsefailure.
