### ISSUE TITLE
Add support to verify client certificates

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-input-lumberjack#31]
Today LSF (client) will verify that server (Logstash with Lumberjack input) it is connecting to is valid. We should extend this to make sure the server is verifying who the client is. This can be done by setting the verify mode to `OpenSSL::SSL::VERIFY_PEER` and using the cert store settings

**Comment by jordansissel** [comment]
Test cases:
* [ ] Self-signed cert
* [ ] CA direct signing a client certificate
* [ ] CA given w/ client providing intermediate and client certificate
* [ ] CA + intermediate certificates w/ client providing only client certificate
* [ ] Multiple trusted CAs w/ different clients providing certs signed by different CAs
* [ ] Multiple trusted CAs with client providing a certificate signed by 2 or more CAs (not sure if we need this one)

**Comment by jordansissel** [comment]
Additionally, should validation extend to validating the subject (CN or subjectAltName IP:a.b.c.d) against the address that is connecting? Should this validation be optional?

For context, SSL clients generally always validate the subject to ensure they are talking not only to a trusted (signed by a trusted CA) server but also to ensure they are talking to the correct server (subject). SSL servers seem to only do this when authentication is required, and in our case this validation is the authentication, so I think we must validate the subject. This makes things more complex for users, though, since this will block tcp tunneling of lsf connections as well as requiring each lsf client to have a certificate with a subject that matches its local IP address that would be seen by the receiving logstash lumberjack input.

**Comment by andrenarchy** [comment]
If the lumberjack input does not verify the client certificate, then any client can connect to any logstash server and feed it with arbitrary data. **This looks like a huge security issue to me.**

The client certificate should be verified against the CA on the logstash server side.

**Comment by jordansissel** [comment]
@andrenarchy This was not part of the original threat model. The threat model used in developing lumberjack/logstash-forwarder was to protect against having sensitive log data leaked _from_ logstash-forwarder to an untrusted source. This project's use of TLS does that by having the client (lsf) validate the server before sending.

We can certainly improve defenses against additional specific threats, such as the one you describe. :)

**Comment by andrenarchy** [comment]
You're right that the other direction is much more sensitive. The threat I described doesn't lead to leaked data but it could be used to take servers down by feeding them huge amounts of data. So I'd still consider this a serious problem.

It's common to check the certificates on both sides, e.g., in OpenVPN, and it shouldn't be difficult to add to the lumberjack input. And the check is already implemented in `logstash-forward`. :)

**Comment by jordansissel** [comment]
> it shouldn't be difficult to add

I wish this were true with _anything_ related to SSL/TLS :(

That said, we are working towards additional (optional) security constraints in filebeat (the successor to this lumberjack/logstash-forwarder). Recommend you open an issue on elastic/filebeat and we can figure out what to do :)

**Comment by andrenarchy** [comment]
Will filebeat still connect to the logstash lumberjack input or will there be a new input on the logstash server side?

**Comment by suyograo** [comment]
@andrenarchy filebeat uses the new [logstash-input-beats](https://www.elastic.co/guide/en/logstash/2.0/plugins-inputs-beats.html) input on LS side

**Comment by andrenarchy** [comment]
@suyograo thx! 

@jordansissel isn't [elastic/filebeat](https://github.com/elastic/filebeat) the client? It already seems to have CA checks (analogous to logstash-forward).

So both the `logstash-input-lumberjack` and `logstash-input-beats` plugins would benefit from client certificate checks against the CA. I'll also open an issue in the `logstash-input-beats` repo.

**Comment by klj613** [comment]
Hello,

This feature is a blocker for me to use Logstash across multiple projects. Been waiting over a year for this feature and last I looked there was pull requests open (on both logstash and lsf) that were idle.

Right now I have to limit access to logstash by IP which makes many projects not able to send logs because the project IP changes daily (AWS).

I look forward to seeing this feature one day.

I might look into implementing it myself if I know the pull requests will be merged (unlike the ones I've seen months ago which were idle).

Thanks,
klj613

**Comment by harbulot** [comment]
@jordansissel 

> Additionally, should validation extend to validating the subject (CN or subjectAltName IP:a.b.c.d) against the address that is connecting? Should this validation be optional?
> 
> For context, SSL clients generally always validate the subject to ensure they are talking not only to a trusted (signed by a trusted CA) server but also to ensure they are talking to the correct server (subject). SSL servers seem to only do this when authentication of clients is required, and in our case this validation is the authentication, so I think we must validate the subject.

That sort of additional verification (matching the IP address or host name from the *client* certificate) is rather unusual. It would rather add quite a lot of complexity in terms of usage (and client certificates are something some people already find quite difficult to understand), without that many benefits.

Of course, client certificates **must** be validated (preferably against a small set of trusted CAs) for this feature to be of any use, but verifying that the host identity in the certificate matches what can be inferred from the connection itself could be over the top, and prevent some legitimate use cases. For example, an outgoing client connection might not necessarily know which interface is being used for what its IP address is going to look like from the other side (e.g. NAT), as you've already pointed out. This is a very different threat model from the verification of the server's identity by the client.

If access should be restricted to a subset of clients that have a trusted certificate, an authorisation layer would probably be better (e.g. a list of authorised DNs). Alternatively, if there's the assumption some clients can no longer be trusted, revocation mechanisms can be used.

Of course, it's generally good practice to allow only a small subset of "better" trusted CAs when verifying a client certificate (and to log its Subject DN too).

**Comment by jordansissel** [comment]
> verifying that the host identity in the certificate matches ... could be over the top, and prevent some legitimate use cases

Such verification could be optional, just as verifying client certs is optional in most scenarios today. :)

> Alternatively, if there's the assumption some clients can no longer be trusted, revocation mechanisms can be used.

I don't think we currently support any revocation mechanisms (CRL, OSCP, etc). Can you open a new ticket to discuss that if you need such a feature?

**Comment by suyograo** [comment]
This has been added in the beats input.. https://github.com/logstash-plugins/logstash-input-beats/pull/56. We are focusing our efforts on Beats input, so will close this issue here.

**Comment by PhaedrusTheGreek** [comment]
@suyograo @jordansissel It seems that we have a gap, if Lumberjack is still the recommended Logstash->Logstash transport, but doesn't support client cert authentication.
