### ISSUE TITLE
logstash 1.5.4 is shipped with 'logstash-input-lumberjack 1.0.4'. blocker

### ISSUE THREAD

**Issue by nxhack** [logstash-plugins/logstash-input-lumberjack#46]
logstash 1.5.4 is shipped with 'logstash-input-lumberjack 1.0.4'. 1.0.4 is blocker. need 1.0.5 soon.  #45

**Comment by jordansissel** [comment]
Thanks for letting us know!

As a workaround, you should be able to upgrade the lumberjack input with `bin/plugin update logstash-input-lumberjack`

**Comment by jordansissel** [comment]
@ph let's make sure 1.0.5 is included with the next release (1.5.5)

**Comment by ph** [comment]
@nxhack thx for finding this, I've released a 1.0.5. 
`bin/plugin update logstash-input-lumbjerjack`

**Comment by nxhack** [comment]
@ph update 1.0.5 , work fine. thank you!

**Comment by jordansissel** [comment]
@nxhack thanks for so quickly getting us feedback on the new release! :heart:

**Comment by stevedearl** [comment]
Hi,

I'm trying to update/install this 1.0.5 version to my logstash 1.5.4 instance but am getting blocked no matter what I try:

So far I've tried:

**Updating the Plugin:**
>C:\Applications\Elastic\logstash-1.5.4\bin>plugin update logstash-input-lumberjack
>io/console not supported; tty will not be manipulated
>ERROR: Updated Aborted, message: Connection refused - Connection refused

**Updating the Plugin from a local download:**
>C:\Applications\Elastic\logstash-1.5.4\bin>plugin update >c:\Downloads\ElasticProducts\Plugins\logstash-input-lumberjack\logstash-input-lumberjack->master.zip
>io/console not supported; tty will not be manipulated
>ERROR: Updated Aborted, message: Plugin c:\Downloads\ElasticProducts\Plugins\logstash-input->lumberjack\logstash-input-lumberjack-master.zip is not installed so it cannot be updated, aborting

**Installing the Plugin:**
>C:\Applications\Elastic\logstash-1.5.4\bin>plugin install logstash-input-lumberjack
>io/console not supported; tty will not be manipulated
>Validating logstash-input-lumberjack
>Unable to download data from https://rubygems.org/ - Errno::ECONNREFUSED: Connection >refused - Connection refused (https://api.rubygems.org/latest_specs.4.8.gz)
>ERROR: Installation aborted, verification failed for logstash-input-lumberjack

**Installing the Plugin from a local Download without Verifying:**
>C:\Applications\Elastic\logstash-1.5.4\bin>plugin install --no-verify >c:\Downloads\ElasticProducts\Plugins\logstash-input-lumberjack\logstash-input-lumberjack->master.zip
>io/console not supported; tty will not be manipulated
>Installing c:\Downloads\ElasticProducts\Plugins\logstash-input-lumberjack\logstash-input->lumberjack-master.zip
>Error Bundler::HTTPError, retrying 1/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 2/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 3/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 4/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 5/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 6/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 7/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 8/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 9/10
>Could not fetch specs from https://rubygems.org/
>Error Bundler::HTTPError, retrying 10/10
>Could not fetch specs from https://rubygems.org/
>Too many retries, aborting, caused by Bundler::HTTPError
>ERROR: Installation Aborted, message: Could not fetch specs from https://rubygems.org/

As you can see from the above, nothing much is working for me at the moment :(

If anyone can let me know what the problem might be that would be very much appreciated.
Apologies in advance if this is a dumb question - I'm still relatively new to Logstash...

Regards,
Steve

**Comment by driskell** [comment]
@stevedearl The repository master.zip is the source, not the gem, so you need to download the gem: https://rubygems.org/gems/logstash-input-lumberjack
Hopefully the local install method will then work when you pass it the gem file :+1:

**Comment by stevedearl** [comment]
Hi @driskell,

Thanks for the quick response. Unfortunately I'd tried that already, as I saw a similar answer to another plugin install thread. It didn't work for me but I didn't document it in my above post as I assumed I'd done something daft!!

Here's what I get when trying to install from the gem file:

>C:\Applications\Elastic\logstash-1.5.4\bin>plugin install >c:\Downloads\ElasticProducts\Plugins\logstash-input-lumberjack\logstash-input-lumberjack->1.0.5.gem
>io/console not supported; tty will not be manipulated
>Validating c:\Downloads\ElasticProducts\Plugins\logstash-input-lumberjack\logstash-input->lumberjack-1.0.5.gem
>Installing logstash-input-lumberjack
>Error Bundler::GemspecError, retrying 1/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 2/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 3/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 4/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 5/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 6/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 7/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 8/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 9/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Error Bundler::GemspecError, retrying 10/10
>There was a Errno::ENOENT while loading logstash-input-lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'
>Too many retries, aborting, caused by Bundler::GemspecError
>ERROR: Installation Aborted, message: There was a Errno::ENOENT while loading logstash-input->lumberjack.gemspec:
>No such file or directory - git from
>  C:/Applications/Elastic/logstash-1.5.4/vendor/local_gems/659b65cd/logstash-input-lumberjack->1.0.5/logstash-input-lumberjack.gemspec:14:in `eval_gemspec'

From the errors, it seems to be the directory/path from **C:/Applications/Elastic/logstash-1.5.4/vendor** which is a problem. I don't have this path or the subdirectories on my machine...?

Any advice appreciated...!

Regards,
Steve

**Comment by stevedearl** [comment]
Sorry,

Just re-checked and the /vendor path is being created correctly (which I guess means the GEM file is being unpacked etc.). 

There is also a **logstash-input-lumberjack.gemspec** file present within the directory - see screenshot attached so I'm still not sure why I'm getting this error ....

![image](https://cloud.githubusercontent.com/assets/13835597/9759812/c1b904c4-56e7-11e5-9b32-b6c73e40d5e1.png)

Cheers,
Steve

**Comment by driskell** [comment]
It mentions `No such file or directory - git`. Maybe it is trying to locate `git`. Do you have it installed? Not sure how it works on Windows to be fair. Someone else may be able to shed more light but it looks like it may be looking for `git`.

**Comment by stevedearl** [comment]
Hi @driskell,

I suspect you're right - line 14 of the gemspec file is:
>s.files = `git ls-files`.split($\)+::Dir.glob('vendor/*')

Unfortunately I'm not git-aware enough to know what the solution is for Windows.....time to hit the internet again... :(

Thanks for the help anyway,
Steve

**Comment by ph** [comment]
Bummer, we have to remove all this `git` from our gemspec.

Do you have some kind of firewall? `bin/plugin update` should work on windows?

**Comment by stevedearl** [comment]
Hi @ph,

I'm in the office so am behind a firewall/proxy. Definitely doesn't work:

>C:\Applications\Elastic\logstash-1.5.4\bin>plugin update logstash-input-lumberjack
>io/console not supported; tty will not be manipulated
>ERROR: Updated Aborted, message: Connection refused - Connection refused

For ElasticSearch plugins (Marvel, BigDesk) I've had to download them locally to get them to install, so I thought it would be the same with this Logstash plugin.

Is there a particular url/address that I'd need to get my IT security team to allow access to to get the standard 'plugin update ....' command to work correctly?

Cheers,
Steve

**Comment by stevedearl** [comment]
Hi All,

Looks like the problem I've hit is already known about:

https://github.com/elastic/logstash/issues/3117

Cheers,
Steve
