### ISSUE TITLE
Logstash Closes Input When Lumberjack Output with JSON Codec Defined

### ISSUE THREAD

**Issue by RyanFrantz** [logstash-plugins/logstash-input-lumberjack#50]
I'm currently relaying events from one Logstash cluster to another via the 'plain' `codec` and noticed that several fields I expected to see in on the other end are not present. So, following the advice from https://github.com/logstash-plugins/logstash-output-lumberjack/issues/3 I updated the `lumberjack` block in my `output` stanza to use the 'json_lines' (even 'json') `codec` and ship events to a TCP listener on `port` '8213'.

The Logstash servers **receiving** relayed events have the following `input` stanza configured:

```
input {

  lumberjack {
    'codec' => 'plain'
    'port' => '9991'
    'ssl_certificate' => '/etc/pki/logstash/lumberjack.crt'
    'ssl_key' => '/etc/pki/logstash/lumberjack.key'
  }

  tcp {
    'codec' => 'json_lines'
    'port' => '8213'
  }

}
```

The **relaying** Logstash servers have the following `output` stanza configured:

```
output {
  # We'll relay events for things like 'wu' and 'tang' to another cluster.
  if [type] in ["wu", "tang"] {
    lumberjack {
      hosts => ["destination01.compay.com", "destination02.company.com"]
      codec => "json_lines"
      port => 8213
      ssl_certificate => "/etc/pki/logstash/lumberjack.crt"
      workers => 1
    }
  } else {
    elasticsearch {
      host => "localhost"
      node_name => "ls.elk01.company.com"
      cluster => "elk"
      index => "%{esindex}"
      manage_template => false
      workers => 16
      protocol => "transport"
      flush_size => 10000
      idle_flush_time => 5
    }
  }

}
```

About 45 seconds after starting Logstash on the relaying hosts, the following message pop into `/var/log/messages` and Logstash stops ingesting:

```
:message=>"CircuitBreaker::rescuing exceptions", :name=>"Lumberjack input", :exception=>LogStash::SizedQueueTimeout::TimeoutError, :level=>:warn}
:message=>"Lumberjack input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and
rejecting new connection until the pipeline recover.", :exception=>LogStash::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
...
:message=>"Lumberjack input: the pipeline is blocked, temporary refusing new connection.", :level=>:warn}
...
```

When I return the **relaying** Logstash config to use the 'plain' `codec` and `port` '9991' all is well.

Am I missing something in my configs?

**NOTE**:  At one point I wondered if the number of output workers needed to be bumped up from '1'; doing so made no difference.

**Comment by RyanFrantz** [comment]
Closing this. It turns out this was a misconfiguration on my part. I needed to set up a new `lumberjack` input using the 'json' `codec`, listening on its own port. Silly me.

**Comment by lokuhetty** [comment]
I have the same problem. Can you elaborate your answer ?
